### ISSUE TITLE
Add cake-contrib user on NuGet.org

### ISSUE THREAD

**Issue by gep13** [BMWilding/Cake.NewRelic#2]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this for Cake.NewRelic? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by gep13** [comment]
@BMWilding just wanted to follow up to see if you had had a chance to give this some thought.  Thanks!

**Comment by BMWilding** [comment]
Sorry @gep13 you caught me on an extended holiday. I've added cake-contrib to the Cake.NewRelic package on nuget.org

**Comment by gep13** [comment]
>@BMWilding said...
I've added cake-contrib to the Cake.NewRelic package on nuget.org

Thank you for doing this!  Can you please confirm what process you took to do this?  I haven't received an email prompting to accept co-ownership of this package.  Thanks.

**Comment by BMWilding** [comment]
I just used the WebUi to add cake-contrib as an owner (Manage Owners >> Username = cake-contrib). I just removed and added cake-contrib again to see if that gets it to trigger the email.

**Comment by gep13** [comment]
Perfect, not sure what happened the first time around.

Thanks!
